### ISSUE TITLE
请教下项目中得mp4文件是怎么生成的

### ISSUE THREAD

**Issue by SunPointed** [mc2012/AndroidTransparentVideo#2]
我已经读了这篇文章https://www.jianshu.com/p/3a0512e2706f

也使用了ffmpeg命令合成需要的mp4，但是mp4是不支持alpha通道的，这个命令
（ffmpeg -i origin.mp4 -vf lutyuv="u=128:v=128" output.mp4）生成的mp4和原mp4合成后的mp4播放大部分都是透明的，请教下怎么获得正确的lef.mp4

**Comment by SunPointed** [comment]
用文章中提供的ffmpeg命令将透明视频和rgb视频合成生成的最终mp4播放时图像右侧有一条黑边，感觉左右两部分（alpha和rgb）没有完全对应上，demo中的wheel是没问题的，请教下这个怎么处理
![微信截图_20200613143143](https://user-images.githubusercontent.com/9999781/84561928-eeaeac80-ad82-11ea-8f64-2939e807cdbc.png)

**Comment by JackyYuenDacai** [comment]
是用亮度当alpha的吧

**Comment by SunPointed** [comment]
@JackyYuenDacai  文件都是ui给的，她是用Adobe After Effects导出的透明的mp4和不透明的mp4，能具体说下吗？

**Comment by JackyYuenDacai** [comment]
他的播放器用的mp4是一边有颜色一边用黑白亮度做alpha层，可能直接用了颜色判断效果不好吧

**Comment by SunPointed** [comment]
感觉关系不大啊，感觉作者demo里的视频很正常

**Comment by SunPointed** [comment]
设置成高精度解决了
